#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202207052258-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.com
# @License           :  LICENSE.md
# @ReadME            :  bashrc --help
# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created           :  Tuesday, Jul 05, 2022 22:58 EDT
# @File              :  bashrc
# @Description       :
# @TODO              :
# @Other             :
# @Resource          :
# @sudo/root         :  no
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export HISTCONTROL='ignoreboth'
export HISTFILE="$HOME/.bash_history"
export HISTSIZE=1000
export HISTTIMEFORMAT='[%F (%X)]: '
export TIMEFORMAT='%3R'
export LS_COLORS='fi=37:di=1;97:ln=90:mh=90:ex=3;2;37:no=1;97:mi=90:ow=91'
export GREP_COLOR='1;91'
export SUDO_EDITOR='/usr/bin/vim'
export TERM='xterm-256color'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Pretty-print man(1) pages.
export LESS_TERMCAP_mb=$'\e[1;91m'
export LESS_TERMCAP_md=$'\e[1;91m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;93m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;92m'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# tmux
export TMUX_HOME="$HOME/.config/tmux"
export TMUX_SHARE_DIR="$HOME/.local/share/tmux"
export TMUX_PLUGIN_MANAGER_PATH="$TMUX_SHARE_DIR/tpm"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# aliases
alias :q='exit'
alias q='exit'
alias t='tmux '
alias v='vim '
alias sv='sudo vim '
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# completions
[ -r "$HOME/.bash_functions" ] && . "$BCFuncs"
[ -r "/usr/share/bash-completion/bash_completion" ] && . "$UsrBashComp"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new-session -A -s main
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
